[package]
name = "mina-tauri"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
rusqlite = "0.29"
tauri = { version = "^2" }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
uuid = { version = "1", features = ["v4"] }
