[package]
name = "mina-tauri"
version = "0.1.0"
edition = "2021"

[dependencies]
tauri = { version = "^2" }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
